### ISSUE TITLE
Upload Failure

### ISSUE THREAD

**Issue by zjs820** [angusws/tcx2nikeplus#10]
I set my garmin workouts and nike+ account as public as instructed but still got this "Error message: Invalid Garmin Activity. Please ensure your garmin workout is not marked as private."

**Comment by daniel-lobo** [comment]
same issue here!

**Comment by daniel-lobo** [comment]
found the solution: instead of putting the link with: https://connect.garmin.com/activity/xxxxxxx, use just http: so http://connect.garmin.com/activity/xxxxxx. It worked like a charm :)

**Comment by lobo** [comment]
SOLVED: make it public in the details of the activity, directly from the garmin website
