### ISSUE TITLE
Nike fuel computation

### ISSUE THREAD

**Issue by sfdye** [angusws/tcx2nikeplus#13]
Hi I am implementing my own syncing service using Python, after successfully uploading GC activity to Nike+, the fuel is always 0. I was wondering, how did you compute the fuel value or Nike computes itself? Thanks!

**Comment by sweh** [comment]
Hi sfdye,

did you solve the Problem. What is the status of your python service? I'm interested in trying it out. I would like to contribute if there are still some problems.

**Comment by sfdye** [comment]
Sorry no luck yet.

On Thu, Sep 8, 2016 at 10:03 PM +0800, "Sebastian Wehrmann" notifications@github.com wrote:

Hi sfdye,

did you solve the Problem. What is the status of your python service? I'm interested in trying it out. I would like to contribute if there are still some problems.
